version: 2
updates:
  - package-ecosystem: swift
    directory: "/"
    schedule:
      interval: daily
    groups:
      elastic-agent:
        patterns:
          - "*apm-agent-ios*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
